# Numpy - Numerical Python

## Advantages of Numpy Arrays:
1. Allows several mathematical operations.
2. Faster operations.

In [1]:
import numpy as np

List vs Numpy- Time Taken

In [2]:
from time import process_time

Time Taken by a list

In [3]:
list = [i for i in range(5000000)]

start_time = process_time()

list = [i*10 for i in list]

end_time = process_time()

time_taken = end_time - start_time
print(f"{time_taken:.20f}")

0.26562500000000000000


In [4]:
np_array = np.array([i for i in range(5000000)])

start_time = process_time()

np_array *= 10 

end_time = process_time()

time_taken = end_time - start_time
print(f"{time_taken:.20f}")


0.00000000000000000000


In [5]:
list = [i for i in range(5)]
print(list)
type(list)

[0, 1, 2, 3, 4]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
#n-dimensional array

In [29]:
listToNP = np.asarray(list)
print(listToNP)
type(listToNP)

[0 1 2 3 4]


numpy.ndarray

In [8]:
np_array.shape

(5,)

In [12]:
#creating a 2 dimensional array
b = np.array([(0,1,2,3,4), (6,7,8,9,10)])
print(b)

[[ 0  1  2  3  4]
 [ 6  7  8  9 10]]


In [13]:
b.shape

(2, 5)

In [15]:
c = np.array([(0,1,2,3,4), (6,7,8,9,10)], dtype=float) 
print(c)

[[ 0.  1.  2.  3.  4.]
 [ 6.  7.  8.  9. 10.]]


In [16]:
#numpy array of zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#numpy array of custom value
z = np.full((4,4), 69)
print(z)

[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]


In [20]:
#Identity matrix
I  = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
#numpy array of random values
r = np.random.random((4, 3))
print(r)

[[0.04585509 0.57561787 0.74539144]
 [0.29192751 0.58304422 0.30093002]
 [0.569508   0.26358468 0.89258585]
 [0.31391569 0.84871012 0.54163105]]


In [23]:
#numpy array of random int values
r = np.random.randint(69,88,(4, 3))
print(r)

[[76 79 69]
 [84 71 87]
 [82 73 78]
 [78 86 72]]


In [24]:
#numpy array of evenly spaced values
d = np.linspace(10, 30, 5)
print(d)

[10. 15. 20. 25. 30.]


In [27]:
# here we are specifying the number of values required at the third position
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [28]:
# here we are specifying the space required at the third position
e = np.arange(10, 30, 6)
print(e)

[10 16 22 28]


Analyzing a numpy array


In [ ]:
f = np.random.randint(10, 100,(5,5))
print(f)

[[59 19 36 18 27]
 [64 35 19 25 25]
 [92 52 21 84 58]
 [56 25 43 30 25]
 [33 89 22 66 84]]


In [31]:
# array dimension
print(f.shape)

(5, 5)


In [32]:
#number of dimensions
print(f.ndim)

2


In [33]:
# number of elemnts in the array
print(f.size)

25


In [34]:
#checking the data type of values in the array
print(f.dtype)

int32


Mathematical operations on a numpy array

In [36]:
list2 = [i for i in range(5, 10)]
print(list2)

[5, 6, 7, 8, 9]


In [38]:
print(list)

[0, 1, 2, 3, 4]


In [40]:
print(list + list2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [45]:
g = np.random.randint(1,10,(5,5))
print(g)

[[2 9 8 3 8]
 [4 1 4 6 2]
 [4 7 2 3 5]
 [6 6 4 6 5]
 [4 4 8 1 1]]


In [46]:
print(f)

[[59 19 36 18 27]
 [64 35 19 25 25]
 [92 52 21 84 58]
 [56 25 43 30 25]
 [33 89 22 66 84]]


In [47]:
print(f + g)

[[61 28 44 21 35]
 [68 36 23 31 27]
 [96 59 23 87 63]
 [62 31 47 36 30]
 [37 93 30 67 85]]


In [48]:
print(f+g)
print(f-g)
print(f*g)
print(f/g)

[[61 28 44 21 35]
 [68 36 23 31 27]
 [96 59 23 87 63]
 [62 31 47 36 30]
 [37 93 30 67 85]]
[[57 10 28 15 19]
 [60 34 15 19 23]
 [88 45 19 81 53]
 [50 19 39 24 20]
 [29 85 14 65 83]]
[[118 171 288  54 216]
 [256  35  76 150  50]
 [368 364  42 252 290]
 [336 150 172 180 125]
 [132 356 176  66  84]]
[[29.5         2.11111111  4.5         6.          3.375     ]
 [16.         35.          4.75        4.16666667 12.5       ]
 [23.          7.42857143 10.5        28.         11.6       ]
 [ 9.33333333  4.16666667 10.75        5.          5.        ]
 [ 8.25       22.25        2.75       66.         84.        ]]


In [50]:
print(np.add(f,g))
print(np.subtract(f,g))
print(np.multiply(f,g))
print(np.divide(f,g))

[[61 28 44 21 35]
 [68 36 23 31 27]
 [96 59 23 87 63]
 [62 31 47 36 30]
 [37 93 30 67 85]]
[[57 10 28 15 19]
 [60 34 15 19 23]
 [88 45 19 81 53]
 [50 19 39 24 20]
 [29 85 14 65 83]]
[[118 171 288  54 216]
 [256  35  76 150  50]
 [368 364  42 252 290]
 [336 150 172 180 125]
 [132 356 176  66  84]]
[[29.5         2.11111111  4.5         6.          3.375     ]
 [16.         35.          4.75        4.16666667 12.5       ]
 [23.          7.42857143 10.5        28.         11.6       ]
 [ 9.33333333  4.16666667 10.75        5.          5.        ]
 [ 8.25       22.25        2.75       66.         84.        ]]


Array Manipulation

In [53]:
#transpose of a matrix
h = np.random.randint(1,10,(5,4))
print(h.shape)
print(h)

(5, 4)
[[1 9 1 9]
 [2 5 7 9]
 [8 6 5 6]
 [2 7 3 4]
 [1 5 3 3]]


In [ ]:
trans = np.transpose(h)
print(trans.shape)
print(trans)

(4, 5)
[[1 2 8 2 1]
 [9 5 6 7 5]
 [1 7 5 3 3]
 [9 9 6 4 3]]


In [55]:
trans2 = trans.T
print(trans2.shape)
print(trans2)

(5, 4)
[[1 9 1 9]
 [2 5 7 9]
 [8 6 5 6]
 [2 7 3 4]
 [1 5 3 3]]


In [57]:
#Reshaping an array
print(h.shape)
print(h)

(5, 4)
[[1 9 1 9]
 [2 5 7 9]
 [8 6 5 6]
 [2 7 3 4]
 [1 5 3 3]]


In [59]:
H = h.reshape(4,5)
print(H)

[[1 9 1 9 2]
 [5 7 9 8 6]
 [5 6 2 7 3]
 [4 1 5 3 3]]
