In [1]:
import numpy as np

In [6]:
#Creating a Matrix using numpy
matrix_1 = np.array([[6,9], [2,1], [8,8]])
print(matrix_1)

[[6 9]
 [2 1]
 [8 8]]


In [7]:
matrix_1.shape

(3, 2)

In [9]:
#Creating matrices with random values

rand_mat = np.random.rand(3,3)
print(rand_mat)

[[0.58063693 0.76183623 0.98964902]
 [0.65719952 0.13297793 0.39611525]
 [0.09863525 0.43853001 0.89664215]]


In [11]:
#Creating matrices with random integers

rand_int_mat = np.random.randint(100, size=(4,5))
print(rand_int_mat)

[[51 53 18 42 21]
 [32 97 16 46 89]
 [23 74 44 60 31]
 [70 86 29 40 88]]


In [13]:
# Matrix with all the values as 1
mat3 = np.ones((2,3))
print(mat3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
mat3 = np.ones((2,3), dtype=int)
print(mat3)

[[1 1 1]
 [1 1 1]]


In [17]:
#Null Matrix
null_mat = np.zeros((6,9), dtype=int)
print(null_mat)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [19]:
# Identity Matrix
id_mat=np.eye(3,4)
print(id_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [22]:
# Identity Matrix
id_mat=np.eye(3,3, dtype=int)
print(id_mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
#Transpose of a matrix
a = np.random.randint(100, size=(4,5))
print(a)

[[38 93 96  7 71]
 [10 93 29 95 28]
 [32 45 83 98 42]
 [52 34 72 56 51]]


In [27]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[38 10 32 52]
 [93 93 45 34]
 [96 29 83 72]
 [ 7 95 98 56]
 [71 28 42 51]]


In [28]:
# Adding 2 Matrices
b = np.random.randint(100, size=(4,5))

In [29]:
print("A=", a)
print("B=", b)


A= [[38 93 96  7 71]
 [10 93 29 95 28]
 [32 45 83 98 42]
 [52 34 72 56 51]]
B= [[72  9 85 86 60]
 [28 91 62 77 78]
 [59  1  5 28 78]
 [74 22 27 42 31]]


In [30]:
sum = a + b
print(sum)

[[110 102 181  93 131]
 [ 38 184  91 172 106]
 [ 91  46  88 126 120]
 [126  56  99  98  82]]


In [32]:
transpose_of_b = np.transpose(b)

In [33]:
print(transpose_of_b)

[[72 28 59 74]
 [ 9 91  1 22]
 [85 62  5 27]
 [86 77 28 42]
 [60 78 78 31]]


In [34]:
sumT = np.add(transpose_of_b, transpose_of_a)
print(sumT)

[[110  38  91 126]
 [102 184  46  56]
 [181  91  88  99]
 [ 93 172 126  98]
 [131 106 120  82]]


In [35]:
difference = a - b
print(difference)

[[-34  84  11 -79  11]
 [-18   2 -33  18 -50]
 [-27  44  78  70 -36]
 [-22  12  45  14  20]]


In [36]:
diffT = np.subtract(transpose_of_b, transpose_of_a)
print(diffT)

[[ 34  18  27  22]
 [-84  -2 -44 -12]
 [-11  33 -78 -45]
 [ 79 -18 -70 -14]
 [-11  50  36 -20]]


In [ ]:
# Multiplication of 2 matrices
"""

The main rule is the number of columns in the first matrix must equal the number of rows in the second matrix.
​If matrix A is m \times n and matrix B is n \times p, their product AB is defined and will be an m \times p matrix.

"""
product = a * b
print(product)

[[2736  837 8160  602 4260]
 [ 280 8463 1798 7315 2184]
 [1888   45  415 2744 3276]
 [3848  748 1944 2352 1581]]


In [40]:
productT = np.dot(a, transpose_of_a)
print(productT)

[[24399 14466 17037 16063]
 [14466 19399 17398 12518]
 [17037 17398 21306 16800]
 [16063 12518 16800 14781]]


In [41]:
product_ = np.multiply(4, a)
product_2 = np.dot(4, a)

In [44]:
print(product_)
print("_______________________________________")
print(product_2)

[[152 372 384  28 284]
 [ 40 372 116 380 112]
 [128 180 332 392 168]
 [208 136 288 224 204]]
_______________________________________
[[152 372 384  28 284]
 [ 40 372 116 380 112]
 [128 180 332 392 168]
 [208 136 288 224 204]]


In [47]:
#Elementwise multiplication but they need to be of same order/shape
product_a_b = np.multiply(a,b)


In [48]:
print(product_a_b)

[[2736  837 8160  602 4260]
 [ 280 8463 1798 7315 2184]
 [1888   45  415 2744 3276]
 [3848  748 1944 2352 1581]]
